export enum AppState {
  IDLE = 'IDLE',
  SCRAPING = 'SCRAPING', // Simulating the Apify step
  ANALYZING = 'ANALYZING', // Sending JSON to Gemini
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR'
}

export interface AnalysisResult {
  universityName: string;
  rawText: string; // The TXT content generated by Gemini
  scrapedJson: string; // The JSON used for analysis (for debugging/viewing)
  groundingChunks?: Array<{
    web?: {
      uri: string;
      title: string;
    };
    maps?: {
      uri: string;
      title: string;
    };
  }>;
}

export interface ScrapeStatus {
  message: string;
  progress: number;
}